provider = "digitalocean"
ssh_private_key = "~/.ssh/vps_rsa"
ssh_public_key = "~/.ssh/vps_rsa.pub"
sleeptime = 1500 # how many milliseconds to wait between API calls (because of request rate limitations)

[providers.digitalocean]
api_key = "abcdefg123xyz"
region = "nyc3"
size = "512mb"
os = "ubuntu-14-04-x64" # slug for Ubuntu 14.04 x64

[providers.vultr]
api_key = "abcdefg123xyz"
region = "1" # 1 = New Jersey
size = "11" # 11 = 512 MB RAM,160 GB SATA,1.00 TB BW
os = "160" # 160 = Ubuntu 14.04 x64

[options]
max_idletime = 15 # minutes
max_uptime = 360 # minutes
vpn_autoconnect = true

