provider = "digitalocean"
ssh_private_key = "~/.ssh/vps_rsa"
ssh_public_key = "~/.ssh/vps_rsa.pub"

[providers.digitalocean]
api_key = "abcdefg123xyz"
region = "ams1"

[providers.vultr]
api_key = "abcdefg123xyz"
region = "5"

[options]
max_idletime = 15 # minutes
max_uptime = 360 # minutes
vpn_autoconnect = true

